services:
  api:
    build:
      context: .
      dockerfile : Dockerfile.dev
    container_name :api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
        - app_network

networks:
  app_network:
