FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir uv


COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --group dev

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBUG=true

EXPOSE 8000

CMD ["bash", "-c", "uv run alembic upgrade head && uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
